// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Fortios.Inputs
{

    public sealed class RouterospfOspfinterfaceMd5KeyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Key ID (1 - 255).
        /// </summary>
        [Input("id")]
        public Input<int>? Id { get; set; }

        /// <summary>
        /// Password for the key.
        /// </summary>
        [Input("keyString")]
        public Input<string>? KeyString { get; set; }

        public RouterospfOspfinterfaceMd5KeyArgs()
        {
        }
        public static new RouterospfOspfinterfaceMd5KeyArgs Empty => new RouterospfOspfinterfaceMd5KeyArgs();
    }
}
