archives:
  - id: archive
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"

before:
  hooks:
    - cd ../..
      make tfgen
      cd .github/workflows

builds:
  - binary: pulumi-resource-fortios
    dir: ../../provider
    main: ./cmd/pulumi-resource-fortios/
    ldflags:
      # The line below MUST align with the module in current provider/go.mod
      - -X github.com/aspyrmedia/pulumi-fortios/provider/pkg/version.Version={{.Tag }}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64

changelog:
  skip: true

release:
  disable: false
  prerelease: auto

snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
